# .github/workflows/mirror.yaml
name: 'mirror'
on:
  push:
    branches:
        - __mirror
  schedule:
    - cron: '15 * * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: mirror
        id: mirror
        uses: craigez/github-mirror-action@f8822eb0aa9fc93ac7e76d5bb7abb46fb07870f4
        with:
          origin: 'https://github.com/craigez/foo'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_REFSPACE: 'refs/heads/mirror/*'
