# .github/workflows/mirror.yaml
name: 'mirror'
on:
  push:
    branches:
        - __mirror
  schedule:
    - cron: '15 * * * *'
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: mirror
        id: mirror
        uses: craigez/github-mirror-action@7603e4304655a977c04b23eb1aa71aa65a5a7aa8
        with:
          origin: 'https://github.com/craigez/foo'
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          TARGET_REFSPACE: 'refs/heads/*:refs/heads/mirror/*'
