name: Comment on Stale Issues
on:
    schedule:
      - cron: '30 0/10 * * *'
  
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
            days-before-close: -1
            days-before-issue-stale: 30
            stale-pr-message: "Add a nice message, can mention maintainers to draw attention"
            stale-issue-message: "Add a nice message, can mention maintainers to draw attention"
            